// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenJobEngine.Infrastructure.Persistence;

#nullable disable

namespace OpenJobEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OpenJobEngineDbContext))]
    [Migration("20260327221150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.CandidateLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Proficiency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId", "LanguageCode");

                    b.ToTable("candidate_languages", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfessionalSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeniorityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YearsOfExperience")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("candidate_profiles", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.CandidateSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProficiencyScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("YearsExperience")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId", "SkillSlug");

                    b.ToTable("candidate_skills", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.JobOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CollectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityFlags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QualityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeniorityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJobId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("DeduplicationKey");

                    b.HasIndex("LastSeenAtUtc");

                    b.HasIndex("Title");

                    b.HasIndex("SourceName", "SourceJobId")
                        .IsUnique();

                    b.ToTable("job_offers", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.JobOfferHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobOfferId", "EventType");

                    b.HasIndex("JobOfferId", "OccurredAtUtc");

                    b.ToTable("job_offer_history_entries", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.JobOfferLanguageRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MinimumProficiency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobOfferId", "LanguageCode");

                    b.ToTable("job_offer_language_requirements", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.JobOfferSkillTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobOfferId", "SkillSlug");

                    b.ToTable("job_offer_skill_tags", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.JobOfferSourceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJobId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobOfferId", "IsActive");

                    b.HasIndex("SourceName", "SourceJobId")
                        .IsUnique();

                    b.ToTable("job_offer_source_observations", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.JobSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastCollectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("job_sources", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.MatchExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AverageScore")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HighMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediumMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TopScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("match_executions", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.ProfileAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastCheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumMatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumNewMatchScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnlyNewJobs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("profile_alerts", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.SavedSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumMatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumNewMatchScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumSalary")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnlyNewJobs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("RemoteOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("saved_searches", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.ScrapeExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedJobs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeactivatedJobs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeduplicatedJobs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCollected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedJobs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceName");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("scrape_executions", (string)null);
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.CandidateLanguage", b =>
                {
                    b.HasOne("OpenJobEngine.Domain.Entities.CandidateProfile", null)
                        .WithMany("Languages")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.CandidateProfile", b =>
                {
                    b.OwnsOne("OpenJobEngine.Domain.ValueObjects.CandidatePreference", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("CandidateProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("AcceptHybrid")
                                .HasColumnType("INTEGER")
                                .HasColumnName("accept_hybrid");

                            b1.Property<bool>("AcceptOnSite")
                                .HasColumnType("INTEGER")
                                .HasColumnName("accept_on_site");

                            b1.Property<bool>("AcceptRemote")
                                .HasColumnType("INTEGER")
                                .HasColumnName("accept_remote");

                            b1.Property<string>("ExcludedCompanyKeywordsCsv")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExcludedWorkModesCsv")
                                .HasColumnType("TEXT");

                            b1.Property<string>("IncludedCompanyKeywordsCsv")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PreferredPrimaryWorkMode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("preferred_work_mode");

                            b1.HasKey("CandidateProfileId");

                            b1.ToTable("candidate_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CandidateProfileId");
                        });

                    b.OwnsOne("OpenJobEngine.Domain.ValueObjects.LocationPreference", "LocationPreference", b1 =>
                        {
                            b1.Property<Guid>("CandidateProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CurrentCity")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("current_city");

                            b1.Property<string>("CurrentCountryCode")
                                .HasMaxLength(16)
                                .HasColumnType("TEXT")
                                .HasColumnName("current_country_code");

                            b1.Property<string>("CurrentRegion")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("current_region");

                            b1.Property<bool>("IsWillingToRelocate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("is_willing_to_relocate");

                            b1.Property<string>("TargetCitiesCsv")
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT")
                                .HasColumnName("target_cities");

                            b1.Property<string>("TargetCountriesCsv")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("target_countries");

                            b1.Property<string>("TargetTimezonesCsv")
                                .HasColumnType("TEXT");

                            b1.HasKey("CandidateProfileId");

                            b1.ToTable("candidate_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CandidateProfileId");
                        });

                    b.OwnsOne("OpenJobEngine.Domain.ValueObjects.SalaryExpectation", "SalaryExpectation", b1 =>
                        {
                            b1.Property<Guid>("CandidateProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .HasMaxLength(16)
                                .HasColumnType("TEXT")
                                .HasColumnName("salary_expectation_currency");

                            b1.Property<decimal?>("MaxAmount")
                                .HasPrecision(12, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("salary_expectation_max");

                            b1.Property<decimal?>("MinAmount")
                                .HasPrecision(12, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("salary_expectation_min");

                            b1.HasKey("CandidateProfileId");

                            b1.ToTable("candidate_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CandidateProfileId");
                        });

                    b.Navigation("LocationPreference")
                        .IsRequired();

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("SalaryExpectation")
                        .IsRequired();
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.CandidateSkill", b =>
                {
                    b.HasOne("OpenJobEngine.Domain.Entities.CandidateProfile", null)
                        .WithMany("Skills")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.JobOfferHistoryEntry", b =>
                {
                    b.HasOne("OpenJobEngine.Domain.Entities.JobOffer", null)
                        .WithMany("HistoryEntries")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.JobOfferLanguageRequirement", b =>
                {
                    b.HasOne("OpenJobEngine.Domain.Entities.JobOffer", null)
                        .WithMany("LanguageRequirements")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.JobOfferSkillTag", b =>
                {
                    b.HasOne("OpenJobEngine.Domain.Entities.JobOffer", null)
                        .WithMany("SkillTags")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.JobOfferSourceObservation", b =>
                {
                    b.HasOne("OpenJobEngine.Domain.Entities.JobOffer", null)
                        .WithMany("SourceObservations")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.ProfileAlert", b =>
                {
                    b.HasOne("OpenJobEngine.Domain.Entities.CandidateProfile", null)
                        .WithMany("Alerts")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.SavedSearch", b =>
                {
                    b.HasOne("OpenJobEngine.Domain.Entities.CandidateProfile", null)
                        .WithMany("SavedSearches")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.CandidateProfile", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Languages");

                    b.Navigation("SavedSearches");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("OpenJobEngine.Domain.Entities.JobOffer", b =>
                {
                    b.Navigation("HistoryEntries");

                    b.Navigation("LanguageRequirements");

                    b.Navigation("SkillTags");

                    b.Navigation("SourceObservations");
                });
#pragma warning restore 612, 618
        }
    }
}
